name: Postman collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *

jobs:
    run-postman-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the code
         uses: actions/checkout@v6.0.1

       - name: Install Node.js and npm
         uses: actions/setup-node@v6.1.0
         with:
          node-version: '22'

       - name: Install newman
         run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

            
       - name: Run the Postman collection
         run: |
              newman run 'Inwarranty-flow Collection.postman_collection.json' \
              -e QA.postman_environment.json \
              -r cli,htmlextra

       - name: Upload report
         if: always()
         uses: actions/upload-artifact@v6.0.0
         with:
           name: Newman Report
           path: newman/*.html

       - name: Creating GitHub page branch
         if: always()
         uses: peaceiris/actions-gh-pages@v4.0.0
         with: 
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: newman/
           
