name: Postman collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *

jobs:
    run-postman-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the code
         uses: actions/checkout@v6.0.1

       - name: Install Node.js and npm
         uses: actions/setup-node@v6.1.0
         with:
          node-version: '22'

       - name: Install newman & htmlextra
         run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

       - name: Run the Postman collection
         run: |
              newman run 'Inwarranty-flow Collection.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,html-extra
